### ISSUE TITLE
Swift packages that include resources accessed via Bundle.module fail to compile with swift_bazel

### ISSUE THREAD

**Issue by AttilaTheFun** [cgrindel/swift_bazel#215]
I'm working on migrating one of my applications from using Xcode + Swift Package Manager to Bazel. A couple of my SPM dependencies include resources like this:

https://github.com/marmelroy/PhoneNumberKit/blob/master/Package.swift

```
        .target(name: "PhoneNumberKit",
                path: "PhoneNumberKit",
                exclude: ["Resources/Original",
                          "Resources/README.md",
                          "Resources/update_metadata.sh",
                          "Info.plist"],
                resources: [
                    .process("Resources/PhoneNumberMetadata.json")
                ]),
```

These are accessed in code via the generated Bundle.module extension.

This results in the module failing to compile like this:
```
external/swiftpkg_phonenumberkit/PhoneNumberKit/Bundle+Resources.swift:35:23: error: type 'Bundle' has no member 'module'
        return Bundle.module
               ~~~~~~ ^~~~~~
external/swiftpkg_phonenumberkit/PhoneNumberKit/Bundle+Resources.swift:35:23: error: type 'Bundle' has no member 'module'
        return Bundle.module
               ~~~~~~ ^~~~~~
```

Is this a known issue? And do you have any suggested workarounds? I might be able to hack around this by forking the code and bundling that json myself but it's definitely a hassle.

**Comment by cgrindel** [comment]
Resource support is on [the list for the 0.3.0 release](https://github.com/cgrindel/swift_bazel/milestone/2). Unfortunately, I do not have a workaround at this time. I plan to work on this next week.

Related to #175

**Comment by AttilaTheFun** [comment]
Awesome! I'll look out for that. In the meantime I can just fork this library and add the resource to the main bundle but I'd like to remove that workaround once resources are properly supported.

**Comment by AttilaTheFun** [comment]
@cgrindel verified this is working in the new 0.3.0 release, thanks!
